# Generated by Django 5.2.3 on 2025-06-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooltemplate',
            name='jsx_template',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quota',
        ),
        migrations.AddField(
            model_name='tooltemplate',
            name='config_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usertool',
            name='config_json',
            field=models.JSONField(default=dict),
        ),
    ]
